spring.datasource.url=jdbc:postgresql://${PGHOST:85.159.27.110}:${PGPORT:5432}/${PGDATABASE:test_enu}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PGUSER:test_role}
spring.datasource.password=${PGPASSWORD:qwerty123@}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:public}
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false
spring.main.allow-circular-references=true

server.port=${PORT:8080}
file.upload-dir=${UPLOAD_DIR:/tmp/uploaded-files}