spring.datasource.url=${DATABASE_URL:jdbc:postgresql://85.159.27.110:5432/test_enu}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:test_role}
spring.datasource.password=${DATABASE_PASSWORD:qwerty123@}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:habits_corp}
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false
spring.main.allow-circular-references=true

server.port=${PORT:8080}
file.upload-dir=${UPLOAD_DIR:/tmp/uploaded-files}